import {
  AiTerminalShapePreview,
  ArtifactShapePreview,
  FileTreeShapePreview,
  SchemaDisplayShapePreview,
  SnippetShapePreview,
  StackTraceShapePreview,
  TestResultsShapePreview,
  WebPreviewShapePreview,
} from "@/components/ai-elements/shape-previews";
import {
  type AiTerminalShape,
  type ArtifactShape,
  aiTerminalShapeProps,
  artifactShapeProps,
  type FileTreeShape,
  fileTreeShapeProps,
  type SchemaDisplayShape,
  type SnippetShape,
  type StackTraceShape,
  schemaDisplayShapeProps,
  snippetShapeProps,
  stackTraceShapeProps,
  type TestResultsShape,
  testResultsShapeProps,
  type WebPreviewShape,
  webPreviewShapeProps,
} from "./ai-elements-shape-props";
import { BaseAiElementsShapeUtil } from "./base-ai-elements-shape-util";

export class ArtifactShapeUtil extends BaseAiElementsShapeUtil<ArtifactShape> {
  static override type = "artifact" as const;
  static override props = artifactShapeProps;

  protected minWidth = 280;
  protected minHeight = 180;

  override getDefaultProps(): ArtifactShape["props"] {
    return {
      w: 560,
      h: 320,
      name: "Artifact",
      description: "Snapshot",
      content: "Deployment preview generated by agent.",
    };
  }

  protected renderContent(shape: ArtifactShape) {
    return <ArtifactShapePreview props={shape.props} />;
  }
}

export class FileTreeShapeUtil extends BaseAiElementsShapeUtil<FileTreeShape> {
  static override type = "file-tree" as const;
  static override props = fileTreeShapeProps;

  protected minWidth = 260;
  protected minHeight = 180;

  override getDefaultProps(): FileTreeShape["props"] {
    return {
      w: 460,
      h: 360,
      name: "File Tree",
      entries: [
        { path: "apps/web/src/components", type: "folder" },
        { path: "apps/web/src/components/header.tsx", type: "file" },
        { path: "apps/web/src/components/deploy-panel.tsx", type: "file" },
        { path: "apps/web/src/lib/sentry.ts", type: "file" },
        { path: "apps/web/src/lib/vercel.ts", type: "file" },
        { path: "tests/e2e/deploy.spec.ts", type: "file" },
      ],
      selectedPath: "apps/web/src/components/deploy-panel.tsx",
      expandedPaths: ["apps", "apps/web", "apps/web/src", "apps/web/src/components"],
    };
  }

  protected renderContent(shape: FileTreeShape) {
    return <FileTreeShapePreview props={shape.props} />;
  }
}

export class SchemaDisplayShapeUtil extends BaseAiElementsShapeUtil<SchemaDisplayShape> {
  static override type = "schema-display" as const;
  static override props = schemaDisplayShapeProps;

  protected minWidth = 320;
  protected minHeight = 240;

  override getDefaultProps(): SchemaDisplayShape["props"] {
    return {
      w: 620,
      h: 420,
      name: "Schema",
      method: "POST",
      path: "/api/deployments",
      description: "Create a deployment and stream build logs back to the canvas.",
      parameters: [
        {
          name: "projectId",
          type: "string",
          required: true,
          description: "Vercel project identifier",
          location: "path",
        },
      ],
      requestFields: [
        { name: "commitSha", type: "string", required: true, description: "Git commit to deploy" },
        { name: "environment", type: "string", required: true, description: "preview or production" },
      ],
      responseFields: [
        { name: "deploymentId", type: "string", required: true, description: "Created deployment ID" },
        { name: "url", type: "string", required: true, description: "Deployment preview URL" },
      ],
    };
  }

  protected renderContent(shape: SchemaDisplayShape) {
    return <SchemaDisplayShapePreview props={shape.props} />;
  }
}

export class SnippetShapeUtil extends BaseAiElementsShapeUtil<SnippetShape> {
  static override type = "snippet" as const;
  static override props = snippetShapeProps;

  protected minWidth = 260;
  protected minHeight = 64;

  override getDefaultProps(): SnippetShape["props"] {
    return {
      w: 560,
      h: 84,
      name: "Snippet",
      prefix: "$",
      language: "bash",
      code: "pnpm test --filter deploy-flow --reporter=dot",
    };
  }

  protected renderContent(shape: SnippetShape) {
    return <SnippetShapePreview props={shape.props} />;
  }
}

export class StackTraceShapeUtil extends BaseAiElementsShapeUtil<StackTraceShape> {
  static override type = "stack-trace" as const;
  static override props = stackTraceShapeProps;

  protected minWidth = 320;
  protected minHeight = 220;

  override getDefaultProps(): StackTraceShape["props"] {
    return {
      w: 660,
      h: 360,
      name: "Stack Trace",
      showInternalFrames: false,
      trace:
        "TypeError: Cannot read properties of undefined (reading 'deployment')\n" +
        "    at createDeployment (apps/web/src/lib/vercel.ts:42:17)\n" +
        "    at runDeployFlow (apps/web/src/lib/deploy-flow.ts:88:9)\n" +
        "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
    };
  }

  protected renderContent(shape: StackTraceShape) {
    return <StackTraceShapePreview props={shape.props} />;
  }
}

export class AiTerminalShapeUtil extends BaseAiElementsShapeUtil<AiTerminalShape> {
  static override type = "ai-terminal" as const;
  static override props = aiTerminalShapeProps;

  protected minWidth = 320;
  protected minHeight = 180;

  override getDefaultProps(): AiTerminalShape["props"] {
    return {
      w: 680,
      h: 380,
      name: "Deploy Logs",
      output:
        "[10:14:23] sentry releases propose-version\n" +
        "[10:14:24] vercel deploy --prebuilt\n" +
        "[10:14:31] Build completed in 7.2s\n" +
        "[10:14:33] Preview: https://acme-dashboard-git-fix.vercel.app",
      isStreaming: false,
      autoScroll: true,
    };
  }

  protected renderContent(shape: AiTerminalShape) {
    return <AiTerminalShapePreview props={shape.props} />;
  }
}

export class TestResultsShapeUtil extends BaseAiElementsShapeUtil<TestResultsShape> {
  static override type = "test-results" as const;
  static override props = testResultsShapeProps;

  protected minWidth = 360;
  protected minHeight = 220;

  override getDefaultProps(): TestResultsShape["props"] {
    return {
      w: 640,
      h: 420,
      name: "Test Results",
      summary: {
        passed: 8,
        failed: 1,
        skipped: 1,
        total: 10,
        duration: 15420,
      },
      tests: [
        { suite: "deploy-flow", name: "creates preview deployment", status: "passed", duration: 840 },
        { suite: "deploy-flow", name: "streams build logs", status: "passed", duration: 1020 },
        {
          suite: "deploy-flow",
          name: "captures stack trace on build failure",
          status: "failed",
          duration: 1340,
          errorMessage: "Expected error breadcrumb count to be > 0",
          errorStack: "at tests/e2e/deploy.spec.ts:182:13",
        },
      ],
    };
  }

  protected renderContent(shape: TestResultsShape) {
    return <TestResultsShapePreview props={shape.props} />;
  }
}

export class WebPreviewShapeUtil extends BaseAiElementsShapeUtil<WebPreviewShape> {
  static override type = "web-preview" as const;
  static override props = webPreviewShapeProps;

  protected minWidth = 360;
  protected minHeight = 240;

  override getDefaultProps(): WebPreviewShape["props"] {
    return {
      w: 700,
      h: 460,
      name: "Web Preview",
      url: "https://example.com",
      logs: [
        {
          level: "log",
          message: "App booted successfully",
          timestamp: new Date().toISOString(),
        },
      ],
    };
  }

  protected renderContent(shape: WebPreviewShape) {
    return <WebPreviewShapePreview props={shape.props} />;
  }
}
